app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true

api:
    resource: "@ApiBundle/Resources/config/routes.yml"
    type:     rest
    prefix:   /api