imports:
    - { resource: services/listeners.yml }
    - { resource: services/extensions.yml }
    - { resource: services/repositories.yml }
    - { resource: services/formatters.yml }
    - { resource: services/controllers.yml }

services:
    markdown:
        class: AppBundle\Utils\Markdown